name : fast-cd

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Ambiente de deployment'     
        required: true
        options: 
        - dev
        - prod
      imageTag:
        required: true
        description: 'Deployment image tag'
        default: 'latest'

jobs:
  deployment:
    runs-on: ubuntu-latest
    env:
      HOST_ENV: ${{ github.event.inputs.environment == 'prod' && '34.224.25.116' || '98.80.128.189' }} 
      SSH_USER: "root"
      SSH_PORT: 22
    steps:
    - run: |
        echo "Ambiente de deployment: ${{ github.event.inputs.environment }}"
        echo "imageTag: ${{ github.event.inputs.imageTag }}"

    - name: Discord Notification
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.WEBHOOK_URL }}
        content: "Deployment do app FAST-CI-CD:**${{ github.event.inputs.imageTag }}** disparado por **${{ github.actor }}** para o ambiente **${{ github.event.inputs.environment }}**"

    - name: Deploy service
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: "${{ env.HOST_ENV }}"
        username: "${{ env.SSH_USER }}"
        key: ${{ secrets.SSH_KEY }}
        port: "${{ env.SSH_PORT }}"
        script: |
          sudo mkdir -p /todo-fast
          sudo docker service rm fast-ci-todo | true
          sudo docker service create --name fast-ci-todo --replicas=3 -p 80:3000 \
            --mount type=bind,source=/todo-fast,destination=/etc/todos \
            hardsource/fast-todo:${{ github.event.inputs.imageTag }}
